import type { DemoEmployee } from '@/lib/demo/types';

/** Effectif fictif de l'établissement Nantes Atlantis. */
export const EMPLOYEES: DemoEmployee[] = [
  {
    id: 'camille-ferrand',
    firstName: 'Camille',
    lastName: 'Ferrand',
    job: 'Responsable univers maison',
    poste: 'enc',
    contract: 'CDI 39 h',
    since: '4 mars 2021',
    status: 'actif',
  },
  {
    id: 'jonas-meyer',
    firstName: 'Jonas',
    lastName: 'Meyer',
    job: 'Adjoint magasin',
    poste: 'enc',
    contract: 'CDI · forfait jours',
    since: '12 sept. 2019',
    status: 'actif',
    forfaitJours: true,
  },
  {
    id: 'remi-chartier',
    firstName: 'Rémi',
    lastName: 'Chartier',
    job: 'Vendeur',
    poste: 'vte',
    contract: 'CDI 35 h',
    since: '2 juin 2022',
    status: 'actif',
  },
  {
    id: 'ines-bakhti',
    firstName: 'Inès',
    lastName: 'Bakhti',
    job: 'Hôtesse de caisse',
    poste: 'cai',
    contract: 'CDI 35 h',
    since: '18 janv. 2023',
    status: 'actif',
  },
  {
    id: 'nour-zaidi',
    firstName: 'Nour',
    lastName: 'Zaidi',
    job: 'Vendeuse décoration',
    poste: 'vte',
    contract: 'CDI 30 h',
    since: '5 oct. 2020',
    status: 'actif',
  },
  {
    id: 'alix-perron',
    firstName: 'Alix',
    lastName: 'Perron',
    job: 'Employé réserve',
    poste: 'res',
    contract: 'CDI 35 h',
    since: '9 mai 2024',
    status: 'actif',
  },
  {
    id: 'elsa-tavares',
    firstName: 'Elsa',
    lastName: 'Tavares',
    job: 'Vendeuse',
    poste: 'vte',
    contract: 'CDD 24 h',
    since: '3 févr. 2026',
    status: 'essai',
  },
  {
    id: 'malik-ouedraogo',
    firstName: 'Malik',
    lastName: 'Ouedraogo',
    job: 'Employé logistique',
    poste: 'liv',
    contract: 'CDI 35 h',
    since: '21 nov. 2018',
    status: 'actif',
  },
  {
    id: 'chloe-vasseur',
    firstName: 'Chloé',
    lastName: 'Vasseur',
    job: 'Vendeuse',
    poste: 'vte',
    contract: 'CDI 20 h',
    since: '14 juil. 2025',
    status: 'actif',
  },
  {
    id: 'yanis-bouchard',
    firstName: 'Yanis',
    lastName: 'Bouchard',
    job: 'Vendeur univers maison',
    poste: 'vte',
    contract: 'CDI 35 h',
    since: '17 août 2026',
    status: 'essai',
  },
  {
    id: 'sarah-lemoine',
    firstName: 'Sarah',
    lastName: 'Lemoine',
    job: 'Vendeuse décoration',
    poste: 'vte',
    contract: 'CDI 30 h',
    since: '7 sept. 2026',
    status: 'essai',
  },
  {
    id: 'hugo-delaunay',
    firstName: 'Hugo',
    lastName: 'Delaunay',
    job: 'Employé retrait web',
    poste: 'clc',
    contract: 'CDI 28 h',
    since: '2 avr. 2023',
    status: 'sortie',
  },
];

export function findEmployee(id: string): DemoEmployee | undefined {
  return EMPLOYEES.find((employee) => employee.id === id);
}
